# Generated by Django 2.2.9 on 2019-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
